language: julia
os:
  - linux
julia:
  - 1.4
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: chenkun0228@gmail.com
# env:
#    - PYTHON=""

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.build("QuantumStatistics")
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

after_success:
- julia -e 'using Pkg;
            Pkg.add("Coverage");
            using Coverage;
            Codecov.submit(Codecov.process_folder())'
